export const TEST_NAME_MAP: Record<string, string> = {
    'addition-subtraction': 'Add/Subtract',
    'multiplication': 'Multiplication',
    'division': 'Division',
    'basic-addition-plus-4': 'Small Sister: +4',
    'basic-addition-plus-40': 'Small Sister: +40',
    'basic-addition-plus-3': 'Small Sister: +3',
    'basic-addition-plus-30': 'Small Sister: +30',
    'basic-addition-plus-2': 'Small Sister: +2',
    'basic-addition-plus-20': 'Small Sister: +20',
    'basic-addition-plus-1': 'Small Sister: +1',
    'basic-addition-plus-10': 'Small Sister: +10',
    'basic-subtraction-minus-4': 'Small Sister: -4',
    'basic-subtraction-minus-40': 'Small Sister: -40',
    'basic-subtraction-minus-3': 'Small Sister: -3',
    'basic-subtraction-minus-30': 'Small Sister: -30',
    'basic-subtraction-minus-2': 'Small Sister: -2',
    'basic-subtraction-minus-20': 'Small Sister: -20',
    'basic-subtraction-minus-1': 'Small Sister: -1',
    'basic-subtraction-minus-10': 'Small Sister: -10',
    'big-brother-addition-plus-9': 'Big Brother: +9',
    'big-brother-addition-plus-90': 'Big Brother: +90',
    'big-brother-addition-plus-8': 'Big Brother: +8',
    'big-brother-addition-plus-80': 'Big Brother: +80',
    'big-brother-addition-plus-7': 'Big Brother: +7',
    'big-brother-addition-plus-70': 'Big Brother: +70',
    'big-brother-addition-plus-6': 'Big Brother: +6',
    'big-brother-addition-plus-60': 'Big Brother: +60',
    'big-brother-addition-plus-5': 'Big Brother: +5',
    'big-brother-addition-plus-50': 'Big Brother: +50',
    'big-brother-addition-plus-4': 'Big Brother: +4',
    'big-brother-addition-plus-40': 'Big Brother: +40',
    'big-brother-addition-plus-3': 'Big Brother: +3',
    'big-brother-addition-plus-30': 'Big Brother: +30',
    'big-brother-addition-plus-2': 'Big Brother: +2',
    'big-brother-addition-plus-20': 'Big Brother: +20',
    'big-brother-addition-plus-1': 'Big Brother: +1',
    'big-brother-addition-plus-10': 'Big Brother: +10',
    'big-brother-subtraction-minus-9': 'Big Brother: -9',
    'big-brother-subtraction-minus-90': 'Big Brother: -90',
    'big-brother-subtraction-minus-8': 'Big Brother: -8',
    'big-brother-subtraction-minus-80': 'Big Brother: -80',
    'big-brother-subtraction-minus-7': 'Big Brother: -7',
    'big-brother-subtraction-minus-70': 'Big Brother: -70',
    'big-brother-subtraction-minus-6': 'Big Brother: -6',
    'big-brother-subtraction-minus-60': 'Big Brother: -60',
    'big-brother-subtraction-minus-5': 'Big Brother: -5',
    'big-brother-subtraction-minus-50': 'Big Brother: -50',
    'big-brother-subtraction-minus-4': 'Big Brother: -4',
    'big-brother-subtraction-minus-40': 'Big Brother: -40',
    'big-brother-subtraction-minus-3': 'Big Brother: -3',
    'big-brother-subtraction-minus-30': 'Big Brother: -30',
    'big-brother-subtraction-minus-2': 'Big Brother: -2',
    'big-brother-subtraction-minus-20': 'Big Brother: -20',
    'big-brother-subtraction-minus-1': 'Big Brother: -1',
    'big-brother-subtraction-minus-10': 'Big Brother: -10',
    'combination-plus-6': 'Combination: +6',
    'combination-plus-60': 'Combination: +60',
    'combination-plus-7': 'Combination: +7',
    'combination-plus-70': 'Combination: +70',
    'combination-plus-8': 'Combination: +8',
    'combination-plus-80': 'Combination: +80',
    'combination-plus-9': 'Combination: +9',
    'combination-plus-90': 'Combination: +90',
    'combination-minus-6': 'Combination: -6',
    'combination-minus-60': 'Combination: -60',
    'combination-minus-7': 'Combination: -7',
    'combination-minus-70': 'Combination: -70',
    'combination-minus-8': 'Combination: -8',
    'combination-minus-80': 'Combination: -80',
    'combination-minus-9': 'Combination: -9',
    'combination-minus-90': 'Combination: -90',
};
